create table clients (
	id bigint generated by default as identity
	, name varchar(255), primary key (id)
);

create table products (
	id bigint generated by default as identity
	, account varchar(255)
	, balance float(53)
	, product_type tinyint check (product_type between 0 and 1)
	, client_id bigint, primary key (id)
);
